import { ChampionClass } from './types';

// Champion Classes
export const Classes: ChampionClass[] = [
  'AD Bruiser', 'AP Bruiser',
  'Burst mage', 'Control mage', 'Poke mage',
  'AD Assasin', 'AP Assasin',
  'Engage Tank', 'Defensive Tank',
  'Utility marksman', 'Carry marksman',
  'Enchanter', '',
];

// Champion class mapping
export const CHAMPION_CLASSES: Record<string, ChampionClass> = {
 // A
  Aatrox: 'AD Bruiser',
  Ahri: 'Burst mage',
  Akali: 'AP Assasin',
  Akshan: 'AD Assasin',
  Alistar: 'Engage Tank',
  Ambessa: 'AD Bruiser',
  Amumu: 'Engage Tank',
  Anivia: 'Control mage',
  Annie: 'Burst mage',
  Aphelios: 'Carry marksman',
  Ashe: 'Utility marksman',
  AurelionSol: 'Control mage',
  Aurora: 'Burst mage',
  Azir: 'Control mage',
  // B
  Bard: 'Enchanter',
  Belveth: 'AD Bruiser',
  Blitzcrank: 'Engage Tank',
  Brand: 'Control mage',
  Braum: 'Defensive Tank',
  Briar: 'AD Bruiser',
  Caitlyn: 'Carry marksman',
  Camille: 'AD Bruiser',
  Cassiopeia: 'Control mage',
  Chogath: 'Defensive Tank',
  Corki: 'Carry marksman',
  Darius: 'AD Bruiser',
  Diana: 'AD Bruiser',
  Draven: 'Carry marksman',
  DrMundo: 'AD Bruiser',
  // E
  Ekko: 'AP Assasin',
  Elise: 'AP Assasin',
  Evelynn: 'AP Assasin',
  Ezreal: 'Carry marksman',
  // F
  Fiddlesticks: 'AP Assasin',
  Fiora: 'AD Bruiser',
  Fizz: 'AP Assasin',
  // G
  Galio: 'AP Bruiser',
  Gangplank: 'AD Bruiser',
  Garen: 'AD Bruiser',
  Gnar: 'AD Bruiser',
  Gragas: 'AP Bruiser',
  Graves: 'AD Bruiser',
  Gwen: 'AP Bruiser',
  // H
  Hecarim: 'AD Bruiser',
  Heimerdinger: 'Control mage',
  Hwei: 'Poke mage',
  // I
  Illaoi: 'AD Bruiser',
  Irelia: 'AD Bruiser',
  Ivern: 'Enchanter',
  // J
  Janna: 'Enchanter',
  JarvanIV: 'AD Bruiser',
  Jax: 'AD Bruiser',
  Jayce: 'AD Bruiser',
  Jhin: 'Utility marksman',
  Jinx: 'Carry marksman',
  // K
  Kaisa: 'Carry marksman',
  Kalista: 'Utility marksman',
  Karma: 'Enchanter',
  Karthus: 'Burst mage',
  Kassadin: 'AP Assasin',
  Katarina: 'AP Assasin',
  Kayle: 'Carry marksman',
  Kayn: 'AD Bruiser',
  Kennen: 'AP Assasin',
  Khazix: 'AD Assasin',
  Kindred: 'Carry marksman',
  Kled: 'AD Bruiser',
  KogMaw: 'Carry marksman',
  KSante: 'Defensive Tank',
  // L
  Leblanc: 'Burst mage',
  LeeSin: 'AD Bruiser',
  Leona: 'Defensive Tank',
  Lillia: 'AP Bruiser',
  Lissandra: 'Burst mage',
  Lucian: 'Carry marksman',
  Lulu: 'Enchanter',
  Lux: 'Poke mage',
  // M
  Malphite: 'Engage Tank',
  Malzahar: 'Control mage',
  Maokai: 'Defensive Tank',
  MasterYi: 'AD Assasin',
  Milio: 'Enchanter',
  MissFortune: 'Utility marksman',
  Mordekaiser: 'AP Bruiser',
  Morgana: 'Control mage',
  Naafiri: 'AD Assasin',
  Nami: 'Enchanter',
  Nasus: 'AD Bruiser',
  Nautilus: 'Engage Tank',
  Neeko: 'Burst mage',
  Nidalee: 'AP Assasin',
  Nilah: 'Carry marksman',
  Nocturne: 'AD Assasin',
  Nunu: 'Engage Tank',
  // O
  Olaf: 'AD Bruiser',
  Orianna: 'Control mage',
  Ornn: 'Engage Tank',
  // P
  Pantheon: 'AD Assasin',
  Poppy: 'Defensive Tank',
  Pyke: 'AD Assasin',
  // Q
  Qiyana: 'AD Assasin',
  Quinn: 'AD Assasin',
  // R
  Rakan: 'Engage Tank',
  Rammus: 'Engage Tank',
  RekSai: 'AD Bruiser',
  Rell: 'Engage Tank',
  Renata: 'Enchanter',
  Renekton: 'AD Bruiser',
  Rengar: 'AD Assasin',
  Riven: 'AD Bruiser',
  Rumble: 'AP Bruiser',
  Ryze: 'Control mage',
  // S
  Samira: 'Carry marksman',
  Sejuani: 'Engage Tank',
  Senna: 'Utility marksman',
  Seraphine: 'Control mage',
  Sett: 'AD Bruiser',
  Shaco: 'AD Assasin',
  Shen: 'Defensive Tank',
  Shyvana: 'AP Bruiser',
  Singed: 'AP Bruiser',
  Sion: 'Engage Tank',
  Sivir: 'Utility marksman',
  Skarner: 'Defensive Tank',
  Smolder: 'Carry marksman',
  Sona: 'Enchanter',
  Soraka: 'Enchanter',
  Swain: 'AP Bruiser',
  Sylas: 'AP Assasin',
  Syndra: 'Control mage',
  // T
  TahmKench: 'Defensive Tank',
  Taliyah: 'Control mage',
  Talon: 'AD Assasin',
  Taric: 'Defensive Tank',
  Teemo: 'Control mage',
  Thresh: 'Defensive Tank',
  Tristana: 'Carry marksman',
  Trundle: 'AD Bruiser',
  Tryndamere: 'AD Bruiser',
  TwistedFate: 'Control mage',
  Twitch: 'Utility marksman',
  // U
  Udyr: 'AD Bruiser',
  Urgot: 'AD Bruiser',
  // V
  Varus: 'Utility marksman',
  Vayne: 'Carry marksman',
  Veigar: 'Control mage',
  Velkoz: 'Poke mage',
  Vex: 'Burst mage',
  Vi: 'AD Assasin',
  Viego: 'AD Assasin',
  Viktor: 'Control mage',
  Vladimir: 'Control mage',
  Volibear: 'AP Bruiser',
  // W
  Warwick: 'AD Bruiser',
  Wukong: 'AD Bruiser',
  // X
  Xayah: 'Carry marksman',
  Xerath: 'Poke mage',
  XinZhao: 'AD Bruiser',
  // Y
  Yasuo: 'Carry marksman',
  Yone: 'Carry marksman',
  Yorick: 'AD Bruiser',
  Yuumi: 'Enchanter',
  // Z
  Zac: 'Engage Tank',
  Zed: 'AD Assasin',
  Zeri: 'Carry marksman',
  Ziggs: 'Poke mage',
  Zilean: 'Enchanter',
  Zoe: 'Poke mage',
  Zyra: 'Control mage',
};

// Get champion class
export function getChampionClass(championId: string): ChampionClass {
  return CHAMPION_CLASSES[championId] || '';
}
