import { Position, PositionInfo } from './types';

// 位置图标来自 CommunityDragon (Riot Games官方资源)
const POSITION_ICON_BASE = 'https://raw.communitydragon.org/latest/plugins/rcp-fe-lol-clash/global/default/assets/images/position-selector/positions';

// 位置信息
export const POSITIONS: PositionInfo[] = [
  { id: 'top', enName: 'Top', zhName: '上路', icon: `${POSITION_ICON_BASE}/icon-position-top.png` },
  { id: 'jungle', enName: 'Jungle', zhName: '打野', icon: `${POSITION_ICON_BASE}/icon-position-jungle.png` },
  { id: 'mid', enName: 'Mid', zhName: '中路', icon: `${POSITION_ICON_BASE}/icon-position-middle.png` },
  { id: 'bot', enName: 'Bot', zhName: '下路', icon: `${POSITION_ICON_BASE}/icon-position-bottom.png` },
  { id: 'support', enName: 'Support', zhName: '辅助', icon: `${POSITION_ICON_BASE}/icon-position-utility.png` },
];

// 英雄位置映射 (基于当前版本常见位置)
export const CHAMPION_POSITIONS: Record<string, Position[]> = {
  // A
  Aatrox: ['top'],
  Ahri: ['mid'],
  Akali: ['mid', 'top'],
  Akshan: ['mid', 'top'],
  Alistar: ['support'],
  Ambessa: ['top'],
  Amumu: ['jungle', 'support'],
  Anivia: ['mid'],
  Annie: ['mid', 'support'],
  Aphelios: ['bot'],
  Ashe: ['bot', 'support'],
  AurelionSol: ['mid'],
  Aurora: ['mid', 'top'],
  Azir: ['mid'],
  // B
  Bard: ['support'],
  Belveth: ['jungle'],
  Blitzcrank: ['support'],
  Brand: ['support', 'mid'],
  Braum: ['support'],
  Briar: ['jungle'],
  Caitlyn: ['bot'],
  Camille: ['top'],
  Cassiopeia: ['mid', 'top'],
  Chogath: ['top', 'mid'],
  Corki: ['mid'],
  Darius: ['top'],
  Diana: ['jungle', 'mid'],
  Draven: ['bot'],
  DrMundo: ['top', 'jungle'],
  // E
  Ekko: ['jungle', 'mid'],
  Elise: ['jungle'],
  Evelynn: ['jungle'],
  Ezreal: ['bot'],
  // F
  Fiddlesticks: ['jungle'],
  Fiora: ['top'],
  Fizz: ['mid'],
  // G
  Galio: ['mid', 'support'],
  Gangplank: ['top'],
  Garen: ['top'],
  Gnar: ['top'],
  Gragas: ['jungle', 'top'],
  Graves: ['jungle'],
  Gwen: ['top'],
  // H
  Hecarim: ['jungle'],
  Heimerdinger: ['mid', 'support', 'top'],
  Hwei: ['mid', 'support'],
  // I
  Illaoi: ['top'],
  Irelia: ['top', 'mid'],
  Ivern: ['jungle'],
  // J
  Janna: ['support'],
  JarvanIV: ['jungle'],
  Jax: ['top', 'jungle'],
  Jayce: ['top', 'mid'],
  Jhin: ['bot'],
  Jinx: ['bot'],
  // K
  Kaisa: ['bot'],
  Kalista: ['bot'],
  Karma: ['support', 'mid'],
  Karthus: ['jungle', 'mid'],
  Kassadin: ['mid'],
  Katarina: ['mid'],
  Kayle: ['top'],
  Kayn: ['jungle'],
  Kennen: ['top'],
  Khazix: ['jungle'],
  Kindred: ['jungle'],
  Kled: ['top'],
  KogMaw: ['bot'],
  KSante: ['top'],
  // L
  Leblanc: ['mid'],
  LeeSin: ['jungle'],
  Leona: ['support'],
  Lillia: ['jungle'],
  Lissandra: ['mid'],
  Lucian: ['bot', 'mid'],
  Lulu: ['support'],
  Lux: ['support', 'mid'],
  // M
  Malphite: ['top', 'support'],
  Malzahar: ['mid'],
  Maokai: ['support', 'jungle'],
  MasterYi: ['jungle'],
  Milio: ['support'],
  MissFortune: ['bot'],
  Mordekaiser: ['top'],
  Morgana: ['support', 'mid'],
  Naafiri: ['mid', 'jungle'],
  Nami: ['support'],
  Nasus: ['top'],
  Nautilus: ['support'],
  Neeko: ['mid', 'support'],
  Nidalee: ['jungle'],
  Nilah: ['bot'],
  Nocturne: ['jungle'],
  Nunu: ['jungle'],
  // O
  Olaf: ['jungle', 'top'],
  Orianna: ['mid'],
  Ornn: ['top'],
  // P
  Pantheon: ['support', 'mid', 'top'],
  Poppy: ['jungle', 'top', 'support'],
  Pyke: ['support'],
  // Q
  Qiyana: ['mid', 'jungle'],
  Quinn: ['top'],
  // R
  Rakan: ['support'],
  Rammus: ['jungle'],
  RekSai: ['jungle'],
  Rell: ['support'],
  Renata: ['support'],
  Renekton: ['top'],
  Rengar: ['jungle', 'top'],
  Riven: ['top'],
  Rumble: ['top', 'mid'],
  Ryze: ['mid'],
  // S
  Samira: ['bot'],
  Sejuani: ['jungle'],
  Senna: ['support', 'bot'],
  Seraphine: ['support', 'mid', 'bot'],
  Sett: ['top', 'support'],
  Shaco: ['jungle'],
  Shen: ['top', 'support'],
  Shyvana: ['jungle'],
  Singed: ['top'],
  Sion: ['top'],
  Sivir: ['bot'],
  Skarner: ['jungle'],
  Smolder: ['bot', 'mid'],
  Sona: ['support'],
  Soraka: ['support'],
  Swain: ['support', 'mid'],
  Sylas: ['mid'],
  Syndra: ['mid'],
  // T
  TahmKench: ['top', 'support'],
  Taliyah: ['jungle', 'mid'],
  Talon: ['mid', 'jungle'],
  Taric: ['support'],
  Teemo: ['top'],
  Thresh: ['support'],
  Tristana: ['bot', 'mid'],
  Trundle: ['jungle', 'top'],
  Tryndamere: ['top'],
  TwistedFate: ['mid'],
  Twitch: ['bot'],
  // U
  Udyr: ['jungle'],
  Urgot: ['top'],
  // V
  Varus: ['bot'],
  Vayne: ['bot', 'top'],
  Veigar: ['mid', 'support'],
  Velkoz: ['support', 'mid'],
  Vex: ['mid'],
  Vi: ['jungle'],
  Viego: ['jungle'],
  Viktor: ['mid'],
  Vladimir: ['mid', 'top'],
  Volibear: ['top', 'jungle'],
  // W
  Warwick: ['jungle', 'top'],
  Wukong: ['jungle', 'top'],
  // X
  Xayah: ['bot'],
  Xerath: ['support', 'mid'],
  XinZhao: ['jungle'],
  // Y
  Yasuo: ['mid', 'top', 'bot'],
  Yone: ['mid', 'top'],
  Yorick: ['top'],
  Yuumi: ['support'],
  // Z
  Zac: ['jungle'],
  Zed: ['mid'],
  Zeri: ['bot'],
  Ziggs: ['bot', 'mid'],
  Zilean: ['support', 'mid'],
  Zoe: ['mid'],
  Zyra: ['support'],
};

// 获取英雄位置
export function getChampionPositions(championId: string): Position[] {
  return CHAMPION_POSITIONS[championId] || [];
}
